"""empty message

Revision ID: a54caf7857b6
Revises: 
Create Date: 2023-10-11 21:02:07.223302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54caf7857b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer_one', sa.String(length=500), nullable=False),
    sa.Column('answer_two', sa.String(length=500), nullable=False),
    sa.Column('answer_three', sa.String(length=500), nullable=True),
    sa.Column('answer_four', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('solution', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('card_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('num_correct', sa.Integer(), nullable=False),
    sa.Column('num_incorrect', sa.Integer(), nullable=False),
    sa.Column('out_of', sa.Integer(), nullable=False),
    sa.Column('time_spent', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('session_type', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trivia_results', sa.String(length=100), nullable=True),
    sa.Column('javascript_stats', sa.String(length=100), nullable=True),
    sa.Column('python_stats', sa.String(length=100), nullable=True),
    sa.Column('react_stats', sa.String(length=100), nullable=True),
    sa.Column('csharp_stats', sa.String(length=100), nullable=True),
    sa.Column('cplusplus_stats', sa.String(length=100), nullable=True),
    sa.Column('java_stats', sa.String(length=100), nullable=True),
    sa.Column('nextjs_stats', sa.String(length=100), nullable=True),
    sa.Column('angular_stats', sa.String(length=100), nullable=True),
    sa.Column('typescript_stats', sa.String(length=100), nullable=True),
    sa.Column('rust_stats', sa.String(length=100), nullable=True),
    sa.Column('general_stats', sa.String(length=100), nullable=True),
    sa.Column('sql_stats', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(length=100), nullable=True),
    sa.Column('back', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['card_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_questions')
    op.drop_table('user_stats')
    op.drop_table('study_sessions')
    op.drop_table('card_sets')
    op.drop_table('users')
    op.drop_table('trivia_questions')
    # ### end Alembic commands ###
